version: '3.7'

services:
    app1:
        container_name: app1
        build: ./services/app-1/
    app2:
        container_name: app2
        build: ./services/app-2/
    app3:
        container_name: app3
        build: ./services/app-3/
    nginx:
        container_name: nginx
        build: ./services/nginx/
        ports:
          - "80:80"
        depends_on: 
          - app1
          - app2
          - app3